# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26096263ba1a50006741cfd19d21681ebacde0506f49a1b8f7b49bcc5e5a7c22fa287f1a7d4f77c3dc2144be3f948b36efa4da14d9b7249139ad582fae034731

test:
  secret_key_base: fae35a80cb0970b40dddceff7acd669c313fae9b9067d3e79855bbb13cff3c7ba0f3a95597406008fdcfcaa497180bae58677df62f871f9d8c84fe8c286ef5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
